// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using Soenneker.Cloudflare.Clamav.OpenApiClient.Health;
using Soenneker.Cloudflare.Clamav.OpenApiClient.Scan;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Cloudflare.Clamav.OpenApiClient
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CloudflareClamavOpenApiClient : BaseRequestBuilder
    {
        /// <summary>The health property</summary>
        public global::Soenneker.Cloudflare.Clamav.OpenApiClient.Health.HealthRequestBuilder Health
        {
            get => new global::Soenneker.Cloudflare.Clamav.OpenApiClient.Health.HealthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The scan property</summary>
        public global::Soenneker.Cloudflare.Clamav.OpenApiClient.Scan.ScanRequestBuilder Scan
        {
            get => new global::Soenneker.Cloudflare.Clamav.OpenApiClient.Scan.ScanRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudflare.Clamav.OpenApiClient.CloudflareClamavOpenApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CloudflareClamavOpenApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
        }
    }
}
#pragma warning restore CS0618
