// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cloudflare.Clamav.OpenApiClient.Models
{
    /// <summary>
    /// Represents a persisted snapshot of a background scan&apos;s lifecycle and outcome.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class VirusScanJobResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The UTC timestamp at which the job completed or failed, or `null` while pending.</summary>
        public DateTimeOffset? CompletedAt { get; set; }
        /// <summary>The UTC timestamp at which the job was created.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>A failure description for a failed job, otherwise `null`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Error { get; set; }
#nullable restore
#else
        public string Error { get; set; }
#endif
        /// <summary>The job identifier in standard dashed GUID format.</summary>
        public Guid? Id { get; set; }
        /// <summary>The result property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cloudflare.Clamav.OpenApiClient.Models.VirusScanResponse? Result { get; set; }
#nullable restore
#else
        public global::Soenneker.Cloudflare.Clamav.OpenApiClient.Models.VirusScanResponse Result { get; set; }
#endif
        /// <summary>One of the serialized values defined by VirusScanJobStatus.</summary>
        public global::Soenneker.Cloudflare.Clamav.OpenApiClient.Models.VirusScanJobResponse_status? Status { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudflare.Clamav.OpenApiClient.Models.VirusScanJobResponse"/> and sets the default values.
        /// </summary>
        public VirusScanJobResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cloudflare.Clamav.OpenApiClient.Models.VirusScanJobResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cloudflare.Clamav.OpenApiClient.Models.VirusScanJobResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cloudflare.Clamav.OpenApiClient.Models.VirusScanJobResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "completedAt", n => { CompletedAt = n.GetDateTimeOffsetValue(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "error", n => { Error = n.GetStringValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "result", n => { Result = n.GetObjectValue<global::Soenneker.Cloudflare.Clamav.OpenApiClient.Models.VirusScanResponse>(global::Soenneker.Cloudflare.Clamav.OpenApiClient.Models.VirusScanResponse.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Cloudflare.Clamav.OpenApiClient.Models.VirusScanJobResponse_status>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("completedAt", CompletedAt);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("error", Error);
            writer.WriteGuidValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Cloudflare.Clamav.OpenApiClient.Models.VirusScanResponse>("result", Result);
            writer.WriteEnumValue<global::Soenneker.Cloudflare.Clamav.OpenApiClient.Models.VirusScanJobResponse_status>("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
